### ISSUE TITLE
How can I run this from terminal if installed from appcenter?

### ISSUE THREAD

**Issue by TinyBabyOwl** [phoneybadger/picker#2]
Trying to set up a shortcut for this, but cannot for the life of me figure out how it gets launched.

**Comment by adithyankv** [comment]
You should be able to launch the program using
```
flatpak run com.github.phoneybadger.picker
```
the same should be true for all flatpak apps installed from the appcenter. You can launch any of them using
```
flatpak run APP_ID
```
and you can use `flatpak list` to see all installed flatpaks and their Application IDs
