### ISSUE TITLE
Set Pick Color as default?

### ISSUE THREAD

**Issue by peteruithoven** [phoneybadger/picker#4]
### Description

When you start Picker the focus is in the color textfield, while I assume people will usually want to pick a new color? Wouldn't it make more sense for the Pick Color button to be focussed so that when you press enter or space after opening the app you start picking?
Or shouldn't it at least be the default action so that when you press enter even from the color textfield you can pick 
a new color?
https://valadoc.org/gtk+-3.0/Gtk.Window.set_default.html

![Screenshot from 2022-06-13 14-29-32@2x](https://user-images.githubusercontent.com/523210/173353835-2a989464-a186-4237-87e2-8d57b7a18f07.png)

Then maybe after picking it would make sense to focus the input field?

### Reference and prior art

With Resizer the default action is the select images button for example. 
![Screenshot from 2022-06-13 14-33-58@2x](https://user-images.githubusercontent.com/523210/173354603-131742b9-2bcc-43fb-bc52-7843b5427c59.png)
https://github.com/peteruithoven/resizer/blob/ea9698f374f80e87b29546429bbcc438596a9422/src/ResizePage.vala#L122-L124

And after you select an image you can press enter to resize, even when the focus is in the width or height textfields. 
https://github.com/peteruithoven/resizer/blob/ea9698f374f80e87b29546429bbcc438596a9422/src/ResizePage.vala#L140-L141

**Comment by adithyankv** [comment]
> Wouldn't it make more sense for the Pick Color button to be focussed so that when you press enter or space after opening the app you start picking?

Yeah that would be a much more sensible default.
