### ISSUE TITLE
Empty state when opened multiple times

### ISSUE THREAD

**Issue by peteruithoven** [phoneybadger/picker#5]
### What happened?

When opening Picker multiple times, all but the first one open in a weird, empty state.

Reproduce:
1. Start Picker
2. Start another Picker

### Screenshots

![Screenshot from 2022-06-13 14-40-05@2x](https://user-images.githubusercontent.com/523210/173355980-cbb6ac13-5b31-43c4-9b4e-8c6e2c3c0d6b.png)

### OS name and version

elementary OS 6.1 Jólnir

### Version

1.0.3

### Additional context

Maybe it shouldn't allow multiple instances to open? Behave more like for example AppCenter?

**Comment by adithyankv** [comment]
What would be the best solution for this? should the layout be fixed for multiple instances or should the app just restrict itself to one instance?

> Maybe it shouldn't allow multiple instances to open? Behave more like for example AppCenter?

Yeah I think this would probably be the more sensible solution. I don't think there are any valid use cases where one might want multiple instances of the app open. With the current architecture of the app, the color preview, history and other properties are going to be shared amongst the instances anyway, so doesn't make much sense to have multiple instances open.
